# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rh3jnpcpd_SwuHDbIWd6RDZ2WYK3gnSh
"""

from this import d


with open('gen.txt', 'w') as out:
	for j in range(3):
		for i in range(9):
			strg = f"""	CPUID
		RDTSC
		; mov [cycs1], edx
		mov [cycs2], eax

		mov ebx, byte array[{4096*i}]
		RDTSCP
		; mov [cyce1], edx
		mov [cyce2], eax
		CPUID

		mov edx, [cycs2]
		mov eax, [cyce2]
		sub eax, edx
		PutLInt eax
		nwln
		
		"""
			out.write(strg)
